# Generated by Django 5.2.7 on 2025-11-21 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_endereco'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
