# Generated by Django 5.2.7 on 2025-11-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_delete_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='data_validade',
        ),
    ]
